name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # For PyPI trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcfitsio-dev \
            wcslib-dev \
            libfftw3-dev \
            libhdf5-dev \
            libboost-dev \
            flex \
            bison \
            libblas-dev \
            liblapack-dev \
            gfortran \
            casacore-dev

      - name: Update version (if manual release)
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -i 's/__version__ = ".*"/__version__ = "${{ github.event.inputs.version }}"/' duckms/__init__.py

      - name: Build package
        run: uv build

      - name: Check package
        run: |
          uv pip install twine
          uv run twine check dist/*

      - name: Publish to Test PyPI
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Upload release artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: dist/
